#!/bin/bash
# Usage: dotfiles <dotfiles path> <hookdotfiles | unlink>

# Ask user what to do if destination file exists.
# $1: destination path
# returns: choice in $answer, or unsets $answer if the choice was invalid
askUser() {
  location=$1
  echo "what do you want to do? [s]kip, [S]kip all, [o]verwrite, [O]verwrite all, [b]ackup, [B]ackup all"
  read answer
  echo $answer | grep -E '^(s|S|o|O|b|B)$' > /dev/null 2>&1
  [ $? -ne 0 ] && unset answer
}

# Create symlink and all parent directories.
# $1: source path
# $2: destination path
createlink() {
  mkdir --parents $(dirname "$2")
  ln -s "$1" "$2"
}

skip() {
  echo skip
}

# Rename the destination file and then create a symlink.
# $1: source path
# $2: destination path
backup() {
  echo backup
  mv "$2"{,.bak}
  createlink "$1" "$2"
}

# Remove destination file before creating a symlink.
# $1: source path
# $2: destination path
overwrite() {
  echo overwrite
  rm -rf "$2"
  createlink "$1" "$2"
}

# Create symlinks for all dotfiles.
hookdotfiles() {
  for link in $(find -name '*.symlink'); do
    relpath=${link#./}
    src=$(pwd)/$relpath
    dest=$HOME/.${relpath#*/}
    dest=${dest%.symlink}
    echo "$src -> $dest"

    if [ -e "$dest" ]; then
      echo "File already exists: $dest"
      if [ -z "$strategy" ]; then
        # so far, the user has not chosen a global strategy
        while [ -z $answer ]; do
          askUser
        done
      fi
      case "$strategy$answer" in
        s|S)  skip ;;
        o|O)  overwrite "$src" "$dest" ;;
        b|B)  backup "$src" "$dest" ;;
      esac

      # set strategy according to user answer
      echo "$answer" | grep -E '^(S|O|B)$' > /dev/null 2>&1
      [ $? -eq 0 ] && strategy=$answer
      unset answer
    else
      createlink "$src" "$dest"
    fi
    echo
  done
}

# Delete symlinks and restore backups if there are any.
unlink() {
  for link in `find -name '*.symlink'`; do
      dest=$HOME/.${link#./*/}
      dest=${dest%.symlink}
      rm "$dest"
      [[ -e "$dest.bak" ]] && mv "$dest"{.bak,}
  done
}

cd "$1"
case "$2" in
  hookdotfiles) hookdotfiles ;;
  unlink) unlink ;;
esac
